---
version: "3.7"

services:
  install_site:
    image: git.maby.dev/organization/install_site:0.2
    ports:
      - "80:80"
    environment:
      - BASE_URL=$BASE_URL
      - EMAIL=$EMAIL
    volumes:
      - ./nginx.conf:/web/prowlarr.conf
      - sites-availables:/sites-availables/
      - certs:/etc/letsencrypt/

  prowlarr:
    build: prowlarr
    restart: unless-stopped
    volumes:
      - config:/config/
    env_file:
      - .env
    networks:
      - default
      - selfhost

volumes:
  config:
  sites-availables:
    external: true
  certs:
    external: true

networks:
  default:
  selfhost:
    external: true
